module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  roots: ['<rootDir>/', '<rootDir>/../test/'],
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
    '^@src/(.*)$': '<rootDir>/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@jira/(.*)$': '<rootDir>/jira/$1',
    '^@parser/(.*)$': '<rootDir>/parser/$1',
    '^@llm/(.*)$': '<rootDir>/llm/$1',
    '^@generator/(.*)$': '<rootDir>/generator/$1',
    '^@export/(.*)$': '<rootDir>/export/$1',
    '^@notifications/(.*)$': '<rootDir>/notifications/$1',
    '^@chatbot/(.*)$': '<rootDir>/chatbot/$1',
    '^@audit/(.*)$': '<rootDir>/audit/$1',
    '^@dashboard/(.*)$': '<rootDir>/dashboard/$1',
    '^@health/(.*)$': '<rootDir>/health/$1',
    '^@utils/(.*)$': '<rootDir>/utils/$1',
    '^@database/(.*)$': '<rootDir>/database/$1',
  },
};
