/**
 * Test Case Entity
 * Represents a generated test case
 */

import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
  OneToMany,
} from 'typeorm';
import { TestStep } from './test-step.entity';

export type TestCaseStatus =
  | 'pending_review'
  | 'approved'
  | 'rejected'
  | 'archived';

@Entity('test_cases')
@Index(['ticket_id'])
@Index(['jira_key'])
@Index(['status'])
@Index(['created_at'])
@Index(['type'])
export class TestCase {
  @PrimaryColumn('uuid')
  id: string; // TC-PROJ-123-001 (formatted)

  @Column({ type: 'uuid' })
  ticket_id: string; // Reference to Jira ticket

  @Column({ type: 'varchar', length: 50 })
  jira_key: string; // e.g., PROJ-123

  @Column({ type: 'varchar', length: 100 })
  project_key: string; // Project code

  @Column({ type: 'varchar', length: 500 })
  title: string; // Test case title

  @Column({ type: 'text' })
  description: string; // Full description

  @Column({
    type: 'enum',
    enum: ['positive', 'negative', 'boundary', 'edge_case'],
  })
  type: string; // Test type

  @Column({
    type: 'enum',
    enum: ['pending_review', 'approved', 'rejected', 'archived'],
    default: 'pending_review',
  })
  status: TestCaseStatus;

  @Column({ type: 'text', nullable: true })
  preconditions: string | null; // Setup required

  @Column({ type: 'text', nullable: true })
  postconditions: string | null; // Cleanup required

  @Column({ type: 'simple-array', nullable: true })
  tags: string[] | null; // module, feature, priority

  @Column({ type: 'uuid' })
  created_by: string; // User who triggered generation

  @Column({ type: 'uuid', nullable: true })
  approved_by: string | null; // User who approved

  @Column({ type: 'text', nullable: true })
  approval_comment: string | null; // Approval/rejection reason

  @Column({ type: 'integer' })
  tokens_used: number; // LLM tokens used

  @Column({ type: 'decimal', precision: 10, scale: 4 })
  cost_eur: number; // Cost in euros

  @Column({ type: 'boolean', default: true })
  ai_generated: boolean; // Generated by AI

  @Column({
    type: 'jsonb',
    nullable: true,
    comment: 'Raw AI response for audit trail',
  })
  raw_ai_response: any;

  @OneToMany(() => TestStep, (step) => step.test_case, {
    cascade: true,
    eager: true,
  })
  steps: TestStep[]; // Test steps

  @CreateDateColumn({ type: 'timestamp' })
  created_at: Date;

  @UpdateDateColumn({ type: 'timestamp' })
  updated_at: Date;

  @Column({ type: 'timestamp', nullable: true })
  approved_at: Date | null;

  @Column({ type: 'timestamp', nullable: true })
  exported_at: Date | null;
}
